CREATE DATABASE atividade2;
USE atividade2;

CREATE TABLE Usuario (
	id_usuario INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL UNIQUE,
	data_cadastro TIMESTAMP NOT NULL,
	data_atualizacao TIMESTAMP NOT NULL
);

SHOW TABLES;