USE atividade3;

SHOW COLUMNS FROM autor;
ALTER TABLE autor
MODIFY COLUMN ano_nascimento INT,
MODIFY COLUMN ano_morte INT;

SHOW COLUMNS FROM livro;
ALTER TABLE livro
MODIFY COLUMN ano_publicacao INT;

SHOW COLUMNS FROM usuario;
ALTER TABLE usuario
MODIFY COLUMN nome VARCHAR(255) NOT NULL,
MODIFY COLUMN email VARCHAR(255) NOT NULL UNIQUE,
MODIFY COLUMN senha VARCHAR(255) NOT NULL; 


